<?php

return [
    [
        'slug' => 'hoan-kiem-pho-co-ve-dem',
        'title' => 'Hoàn Kiếm — Phố cổ về đêm',
        'tagline' => '3N2Đ · Từ 2.890.000đ',
        'duration' => '3 ngày 2 đêm',
        'nights' => 2,
        'from_price' => 2890000,
        'district' => 'Hoàn Kiếm',
        'price_min' => 1000000,
        'price_max' => 3500000,
        'image' => 'https://images.unsplash.com/photo-1555921015-5532091f6026?w=1400&q=80',
        'description' => 'Khám phá 36 phố phường, dạo bộ Hồ Gươm về đêm, thưởng thức ẩm thực phố cổ và tận hưởng không gian Pháp cổ điển ngay trung tâm Hà Nội.',
        'highlights' => ['Phố đi bộ Hồ Gươm', 'Phố cổ Hàng Bạc – Hàng Mã', 'Cầu Thê Húc – Đền Ngọc Sơn', 'Bún chả – Phở – Cà phê trứng'],
    ],
    [
        'slug' => 'tay-ho-retreat',
        'title' => 'Tây Hồ Retreat',
        'tagline' => '2N1Đ · 1.490.000đ',
        'duration' => '2 ngày 1 đêm',
        'nights' => 1,
        'from_price' => 1490000,
        'district' => 'Tây Hồ',
        'price_min' => 800000,
        'price_max' => 2500000,
        'image' => 'https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=1400&q=80',
        'description' => 'Thư giãn bên Hồ Tây thơ mộng, đạp xe quanh đường Thanh Niên, ghé chùa Trấn Quốc và thưởng thức buffet hải sản view hồ.',
        'highlights' => ['Chùa Trấn Quốc', 'Đường Thanh Niên ven hồ', 'Bãi đá sông Hồng', 'Buffet Sen Tây Hồ'],
    ],
    [
        'slug' => 'ba-dinh-lang-bac',
        'title' => 'Ba Đình — Lăng Bác',
        'tagline' => '2N1Đ · 1.690.000đ',
        'duration' => '2 ngày 1 đêm',
        'nights' => 1,
        'from_price' => 1690000,
        'district' => 'Ba Đình',
        'price_min' => 900000,
        'price_max' => 3000000,
        'image' => 'https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=1400&q=80&sig=badinh',
        'description' => 'Tour văn hóa lịch sử: viếng Lăng Chủ tịch Hồ Chí Minh, tham quan Hoàng thành Thăng Long, Văn Miếu Quốc Tử Giám.',
        'highlights' => ['Lăng Chủ tịch Hồ Chí Minh', 'Hoàng thành Thăng Long', 'Văn Miếu Quốc Tử Giám', 'Bảo tàng Mỹ thuật'],
    ],
    [
        'slug' => 'long-bien-bai-giua',
        'title' => 'Long Biên — Bãi giữa',
        'tagline' => '3N2Đ · 2.190.000đ',
        'duration' => '3 ngày 2 đêm',
        'nights' => 2,
        'from_price' => 2190000,
        'district' => 'Long Biên',
        'price_min' => 500000,
        'price_max' => 2000000,
        'image' => 'https://images.unsplash.com/photo-1542640244-7e672d6cef4e?w=1400&q=80',
        'description' => 'Trải nghiệm khác biệt: cầu Long Biên lịch sử, picnic bãi giữa sông Hồng, ngắm hoàng hôn và khám phá làng nghề ven sông.',
        'highlights' => ['Cầu Long Biên', 'Bãi giữa sông Hồng', 'Làng gốm Bát Tràng', 'Phố ẩm thực Bồ Đề'],
    ],
    [
        'slug' => 'ha-dong-eco',
        'title' => 'Hà Đông Eco',
        'tagline' => '2N1Đ · 990.000đ',
        'duration' => '2 ngày 1 đêm',
        'nights' => 1,
        'from_price' => 990000,
        'district' => 'Hà Đông',
        'price_min' => 400000,
        'price_max' => 1500000,
        'image' => 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=1400&q=80',
        'description' => 'Tour nghỉ dưỡng tiết kiệm: làng lụa Vạn Phúc, công viên Yên Sở, không gian xanh Mỹ Đình. Phù hợp gia đình và nhóm bạn.',
        'highlights' => ['Làng lụa Vạn Phúc', 'Công viên Yên Sở', 'Hồ Văn Quán', 'Chợ đêm cuối tuần'],
    ],
];
